# Generated by Django 4.0.3 on 2022-04-25 01:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('practical', 'PRACTICAL'), ('theoretical', 'THEORETICAL'), ('fundamental research', 'FUNDAMENTAL RESEARCH'), ('imperical', 'IMPERICAL')], default='practical', max_length=30)),
                ('field', models.CharField(max_length=100)),
                ('keyword_list', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('completed', 'COMPLETED'), ('ongoing', 'ONGOING'), ('planned', 'PLANNED')], default='planned', max_length=30)),
                ('rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                ('snapshot', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_catalog.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
