# Generated by Django 4.0.3 on 2022-04-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('practical', 'PRACTICAL'), ('theoretical', 'THEORETICAL'), ('fundamental research', 'FUNDAMENTAL RESEARCH'), ('imperical', 'IMPERICAL')], default='practical', max_length=30)),
                ('field', models.CharField(max_length=100)),
                ('keyword_list', models.CharField(max_length=200, verbose_name='Keyword List (Seperate with commas)')),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('completed', 'COMPLETED'), ('ongoing', 'ONGOING'), ('planned', 'PLANNED')], default='planned', max_length=30)),
                ('snapshot', models.ImageField(default='default.jpg', upload_to='project_photos')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_catalog.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
