# Generated by Django 4.0.3 on 2022-04-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('delete_user_item', 'Delete own item'), ('change_user_item', 'Change own item'), ('rate_item', 'Rate item'))},
        ),
    ]
