# Generated by Django 4.0.3 on 2022-04-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
