# Generated by Django 4.0.3 on 2022-04-28 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_catalog', '0010_item_likes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Completed', 'COMPLETED'), ('Ongoing', 'ONGOING'), ('Planned', 'PLANNED')], default='planned', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Practical', 'PRACTICAL'), ('Theoretical', 'THEORETICAL'), ('Fundamental research', 'FUNDAMENTAL RESEARCH'), ('Imperical', 'IMPERICAL')], default='practical', max_length=30),
        ),
    ]
