# Generated by Django 4.0.3 on 2022-04-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0012_remove_item_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rate',
        ),
    ]
