# Generated by Django 4.0.3 on 2022-05-07 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_catalog', '0016_rename_rating_rating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Practical', 'PRACTICAL'), ('Theoretical', 'THEORETICAL'), ('Fundamental research', 'FUNDAMENTAL RESEARCH'), ('Empirical', 'Empirical')], default='practical', max_length=30),
        ),
        migrations.CreateModel(
            name='ItemFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_blame', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_target', to='item_catalog.item')),
            ],
        ),
    ]
