# Generated by Django 4.0.3 on 2022-05-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0017_alter_item_type_itemflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
