# Generated by Django 4.0.3 on 2022-05-07 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_catalog', '0018_item_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemflag',
            name='blame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_item_flag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemflag',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_item_target', to='item_catalog.item'),
        ),
    ]
