# Generated by Django 4.0.4 on 2022-05-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0017_alter_item_type'),
        ('item_catalog', '0019_alter_itemflag_blame_alter_itemflag_item'),
    ]

    operations = [
    ]
