# Generated by Django 4.0.3 on 2022-04-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('Add Member', 'add_member'), ('Add Any Item', 'add_any_item'), ('Add User', 'add_user'), ('Delete User', 'delete_user'), ('Block User', 'block_user'), ('Warn User', 'warn_user'), ('Flag User', 'flag_user'), ('Change User Group', 'chgrp_user')),
            },
        ),
    ]
