# Generated by Django 4.0.3 on 2022-04-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepermissions',
            options={'permissions': (('Add Item', 'add_item'), ('Delete Item', 'delete_item'), ('Edit Item', 'edit_item'), ('Rate Item', 'rate_item'), ('Comment', 'comment'), ('Message Users', 'chat'), ('Add Member', 'add_member'), ('Delete Member', 'delete_member'), ('Block Member', 'block_member'), ('Warn Member', 'warn_member'), ('Add Any Item', 'add_any_item'), ('Remove Any Item', 'remove_any_item'), ('Edit Any Item', 'edit_any_item'), ('Add User', 'add_user'), ('Delete User', 'delete_user'), ('Block User', 'block_user'), ('Warn User', 'warn_user'), ('Flag User', 'flag_user'), ('Change User Group', 'chgrp_user'))},
        ),
    ]
