# Generated by Django 4.0.3 on 2022-04-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_sitepermissions_options'),
    ]

    operations = [
    ]
