# Generated by Django 4.0.3 on 2022-04-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20220425_0158'),
    ]

    operations = [
    ]
