# Generated by Django 4.0.3 on 2022-04-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20220425_0159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitePermissions',
        ),
    ]
