# Generated by Django 4.0.3 on 2022-04-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0006_delete_sitepermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('Block User', 'block_user'), ('Warn User', 'warn_user'), ('Flag User', 'flag_user')),
            },
        ),
    ]
