# Generated by Django 4.0.3 on 2022-04-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepermissions',
            options={'permissions': (('block_user', 'Block User'), ('warn_user', 'Warn User'), ('flag_user', 'Flag User'))},
        ),
    ]
