# Generated by Django 4.0.3 on 2022-04-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_sitepermissions_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitePermissions',
        ),
    ]
