# Generated by Django 4.0.3 on 2022-04-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_sitepermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepermissions',
            options={'permissions': (('block_user', 'Block User'), ('flag_user', 'Flag User'), ('view_dashboard', 'View dashboard'))},
        ),
    ]
