# Generated by Django 4.0.4 on 2022-05-10 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0014_userflag_delete_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepermissions',
            options={'permissions': (('block_user', 'Block User'), ('view_dashboard', 'View dashboard'))},
        ),
        migrations.AlterField(
            model_name='userflag',
            name='blame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_user_blame', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userflag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_user_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
