# Generated by Django 4.0.3 on 2022-04-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('add_member', 'Add member'), ('delete_member', 'Add member'), ('block_member', 'Block member'), ('warn_member', 'Warn member'))},
        ),
    ]
