# Generated by Django 4.0.3 on 2022-04-26 02:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_warning_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
