# Generated by Django 4.0.3 on 2022-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_profile_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-user.png', upload_to='profile_pics'),
        ),
    ]
