# Generated by Django 4.0.3 on 2022-05-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('add_member', 'Add member'), ('delete_member', 'Delete member'), ('block_member', 'Block member'), ('warn_member', 'Warn member'))},
        ),
    ]
