# Generated by Django 4.0.4 on 2022-04-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_profile_email_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
