# Generated by Django 4.0.4 on 2022-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('add_member', 'Add member'), ('delete_member', 'Delete member'), ('block_member', 'Block member'), ('warn_member', 'Warn member'), ('flag_member', 'Flag member'), ('view_member_dashboard', 'View member dashboard'))},
        ),
    ]
